fix(windows): fix for setenv() on Windows (#4381)
Microsoft's runtime library doesn't support the standard setenv()
function. _putenv_s() should be used instead.

Without fix iv do not compiling:
`E:\GH\OpenImageIO\src\iv\ivmain.cpp(119,9): error C3861: 'setenv':
identifier not found [E:\GH\OpenImageIO\build\src\iv\iv.vcxproj]`

---------

Signed-off-by: Vlad (Kuzmin) Erium <libalias@gmail.com>