deal with vs 2015 being pedantic about alignment issues.
It still breaks compiling  tryConvert(...) as it wasnt to call tryConvert(T) rathern than tryConvert(const T&)

s:\storage\git\oiio.git\src\include\openimageio\tinyformat.h(178): error C2718: 'const OpenImageIO::v1_7::simd::int4': actual parameter with requested alignment of 16 won't be aligned
s:\storage\git\oiio.git\src\include\openimageio\tinyformat.h(600): note: see reference to class template instantiation 'tinyformat::detail::is_convertible<const T &,int>' being compiled
        with
        [
            T=OpenImageIO::v1_7::simd::int4
        ]
s:\storage\git\oiio.git\src\include\openimageio\tinyformat.h(883): note: see reference to function template instantiation 'void tinyformat::detail::FormatIterator::accept<T1>(const T &)' being compiled
        with
        [
            T1=OpenImageIO::v1_7::simd::int4,
            T=OpenImageIO::v1_7::simd::int4
        ]
s:\storage\git\oiio.git\src\include\openimageio\tinyformat.h(944): note: see reference to function template instantiation 'void tinyformat::detail::format<T1,T2>(tinyformat::detail::FormatIterator &,const T1 &,const T2 &)' being compiled
        with
        [
            T1=OpenImageIO::v1_7::simd::int4,
            T2=OpenImageIO::v1_7::simd::int4
        ]
S:\storage\git\oiio.git\src\include\OpenImageIO/strutil.h(91): note: see reference to function template instantiation 'void tinyformat::format<T1,T2>(std::ostream &,const char *,const T1 &,const T2 &)' being compiled
        with
        [
            T1=OpenImageIO::v1_7::simd::int4,
            T2=OpenImageIO::v1_7::simd::int4
        ]
S:\storage\git\oiio.git\src\libutil\simd_test.cpp(420): note: see reference to function template instantiation 'std::string OpenImageIO::v1_7::Strutil::format<OpenImageIO::v1_7::simd::int4,OpenImageIO::v1_7::simd::int4>(const char *,const T1 &,const T2 &)' being compiled
        with
        [
            T1=OpenImageIO::v1_7::simd::int4,
            T2=OpenImageIO::v1_7::simd::int4
        ]